package com.example.datospersona;

public interface Constants {

    String INTENT_NAME_KEY = "name";
    String INTENT_SURENAMES_KEY = "surname";
    String INTENT_AGE_KEY = "age";
    String INTENT_PHONE_KEY = "phone";
    String INTENT_DRIVING_LICENSE_KEY = "drivingLicense";
    String INTENT_ENGLISH_LEVEL_KEY = "englishLevel";
    String INTENT_DATE_KEY = "date";

    String MAIN_ACTIVITY_USER_LIST_STATUS = "MAIN_ACTIVITY_USER_LIST_STATUS";

    String LANZA_ACTIVIDAD_AGE_STATUS = "LANZA_ACTIVIDAD_AGE_STATUS";
    String LANZA_ACTIVIDAD_NAME_STATUS = "LANZA_ACTIVIDAD_NAME_STATUS";
    String LANZA_ACTIVIDAD_DATE_STATUS = "LANZA_ACTIVIDAD_DATE_STATUS";
    String LANZA_ACTIVIDAD_PHONE_STATUS = "LANZA_ACTIVIDAD_PHONE_STATUS";
    String LANZA_ACTIVIDAD_SURNAME_STATUS = "LANZA_ACTIVIDAD_SURNAME_STATUS";
    String LANZA_ACTIVIDAD_ENGLISH_LEVEL_STATUS = "LANZA_ACTIVIDAD_ENGLISH_LEVEL_STATUS";
    String LANZA_ACTIVIDAD_DRIVING_LICENSE_STATUS = "LANZA_ACTIVIDAD_DRIVING_LICENSE_STATUS";
}
