package com.gandalfran.datospersonalist;

public interface Constants {
    String PERSON_KEY = "person";
    String POSITION_KEY = "position";
    String IS_MODIFY = "isModification";

    String MAIN_ACTIVITY_USER_LIST_STATUS = "MAIN_ACTIVITY_USER_LIST_STATUS";

    String LANZA_ACTIVIDAD_AGE_STATUS = "LANZA_ACTIVIDAD_AGE_STATUS";
    String LANZA_ACTIVIDAD_NAME_STATUS = "LANZA_ACTIVIDAD_NAME_STATUS";
    String LANZA_ACTIVIDAD_DATE_STATUS = "LANZA_ACTIVIDAD_DATE_STATUS";
    String LANZA_ACTIVIDAD_PHONE_STATUS = "LANZA_ACTIVIDAD_PHONE_STATUS";
    String LANZA_ACTIVIDAD_SURNAME_STATUS = "LANZA_ACTIVIDAD_SURNAME_STATUS";
    String LANZA_ACTIVIDAD_ENGLISH_LEVEL_STATUS = "LANZA_ACTIVIDAD_ENGLISH_LEVEL_STATUS";
    String LANZA_ACTIVIDAD_DRIVING_LICENSE_STATUS = "LANZA_ACTIVIDAD_DRIVING_LICENSE_STATUS";
}
